#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
#include "images/square.h"
#include "images/start.h"
#include "images/win.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
typedef enum {
  START,
  STARTBG,
  PLAY,
  WIN,
} GBAState;

Player p = {15, 75, 10, 10, 0};
Enemy e = {98, 10, 10, 10, 2, 0};
Enemy e1 = {118, 140, 10, 10, 2, 0};
Enemy e2 = {138, 10, 10, 10, 2, 0};
Coin c = {120, 75, 5, 5, 1};
Coin c1 = {120, 11, 5, 5, 1};
Coin c2 = {120, 144, 5, 5, 1};
Goal g = {200, 60, 40, 40};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  //videoBuffer[1208] = 0x7fff;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  GBAState state = START;

  int deaths = 0;
  int coins = 0;
  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {
      case START:
        waitForVBlank();
        drawFullScreenImageDMA(start);
        state = STARTBG;
        break;
      case STARTBG:
        if (KEY_DOWN(BUTTON_START, currentButtons)) {
          state = PLAY;
        }
        break;
      case PLAY:
        waitForVBlank();
        fillScreenDMA(LIGHTBLUE);
        //drawRectDMA(p.y, p.x, p.h, p.w, RED);
        drawRectDMA(60, 0, 40, 40, LIGHTGREEN);
        drawRectDMA(g.y, g.x, g.h, g.w, LIGHTGREEN);
        drawImageDMA(p.y, p.x, p.h, p.w, square);
        if (c.state) {
          drawRectDMA(c.y, c.x, c.h, c.w, YELLOW);
        }
        if (c1.state) {
          drawRectDMA(c1.y, c1.x, c1.h, c1.w, YELLOW);
        }
        if (c2.state) {
          drawRectDMA(c2.y, c2.x, c2.h, c2.w, YELLOW);
        }
        drawRectDMA(e.y, e.x, e.h, e.w, BLUE);
        drawRectDMA(e1.y, e1.x, e1.h, e1.w, BLUE);
        drawRectDMA(e2.y, e2.x, e2.h, e2.w, BLUE);
        drawString(150, 2, "Coins:", BLACK);
        drawChar(150, 40, coins + 48, BLACK);
        drawString(150, 185, "Deaths:", BLACK);
        drawChar(150, 230, deaths + 48, BLACK);

        if (e.y == 10) {
          e.state = 0;
        } else if (e.y == 140) {
          e.state = 1;
        } 
        
        if (e.state) {
          e.y -= e.speed;
        } else if (!e.state) {
          e.y += e.speed;
        }

        if (e1.y == 10) {
          e1.state = 0;
        } else if (e1.y == 140) {
          e1.state = 1;
        } 
        
        if (e1.state) {
          e1.y -= e1.speed;
        } else if (!e1.state) {
          e1.y += e1.speed;
        }

        if (e2.y == 10) {
          e2.state = 0;
        } else if (e2.y == 140) {
          e2.state = 1;
        } 
        
        if (e2.state) {
          e2.y -= e2.speed;
        } else if (!e2.state) {
          e2.y += e2.speed;
        }

        if (KEY_DOWN(BUTTON_DOWN, BUTTONS)) {
          if (p.y < 140) {
            p.y++;
          }
        }
        if (KEY_DOWN(BUTTON_UP, BUTTONS)) {
          if (p.y > 10) {
            p.y--;
          }
        }
        if (KEY_DOWN(BUTTON_LEFT, BUTTONS)) {
          if (p.x > 0) {
            p.x--;
          }
        }
        if (KEY_DOWN(BUTTON_RIGHT, BUTTONS)) {
          if (p.x < 230) {
            p.x++;
          }
        }

        if (KEY_DOWN(BUTTON_SELECT, BUTTONS)) {
          state = START;
          p.x = 15;
          p.y = 75;
          coins = 0;
          deaths = 0;
          c.state = 1;
          c1.state = 1;
          c2.state = 1;
        }

        if ((p.x < e.x + e.w) && (p.x + p.w > e.x) && (p.y < e.y + e.h) && (p.h + p.y > e.y)) {
          state = PLAY;
          deaths++;
          p.x = 15;
          p.y = 75;
          coins = 0;
          c.state = 1;
          c1.state = 1;
          c2.state = 1;
        }

        if ((p.x < e1.x + e1.w) && (p.x + p.w > e1.x) && (p.y < e1.y + e1.h) && (p.h + p.y > e1.y)) {
          state = PLAY;
          deaths++;
          p.x = 15;
          p.y = 75;
          coins = 0;
          c.state = 1;
          c1.state = 1;
          c2.state = 1;
        }

        if ((p.x < e2.x + e2.w) && (p.x + p.w > e2.x) && (p.y < e2.y + e2.h) && (p.h + p.y > e2.y)) {
          state = PLAY;
          deaths++;
          p.x = 15;
          p.y = 75;
          coins = 0;
          c.state = 1;
          c1.state = 1;
          c2.state = 1;
        }

        if ((p.x < g.x + g.w) && (p.x + p.w > g.x) && (p.y < g.y + g.h) && (p.h + p.y > g.y)) {
          if (coins == 3) {
            state = WIN;
          }
        }

        if (c.state && (p.x < c.x + c.w) && (p.x + p.w > c.x) && (p.y < c.y + c.h) && (p.h + p.y > c.y)) {
          coins++;
          c.state = 0;
        }

        if (c1.state && (p.x < c1.x + c1.w) && (p.x + p.w > c1.x) && (p.y < c1.y + c1.h) && (p.h + p.y > c1.y)) {
          coins++;
          c1.state = 0;
        }

        if (c2.state && (p.x < c2.x + c2.w) && (p.x + p.w > c2.x) && (p.y < c2.y + c2.h) && (p.h + p.y > c2.y)) {
          coins++;
          c2.state = 0;
        }


        break;
      case WIN:
        waitForVBlank();
        drawFullScreenImageDMA(win);
        if (KEY_DOWN(BUTTON_SELECT, BUTTONS)) {
          state = START;
          p.x = 15;
          p.y = 75;
          coins = 0;
          c.state = 1;
          c1.state = 1;
          c2.state = 1;
          deaths = 0;
        }
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
